name: open_chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluent_ui: ^4.4.0
  dio: ^5.1.2
  http: ^0.13.4
  dio_cache_interceptor: ^3.4.1
  bitsdojo_window: ^0.1.5
  flutter_syntax_view: 
      git:
        url: https://github.com/YehudaKremer/flutter_syntax_view.git
  flutter_acrylic: ^1.1.0
  crypto: ^3.0.3
  simple_animations: ^5.0.0+3
  platform_device_id: ^1.0.1
  file_selector: ^0.9.3
  json_annotation: ^4.8.0
  image_compression_flutter: ^1.0.3
  flutter_screenutil: ^5.8.2
  sqlite3: ^1.11.1
  path: ^1.8.3
  sqlite3_flutter_libs: ^0.5.15
  logger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: OPenChatFonts
      fonts:
        - asset: assets/fonts/SourceHanSans-Normal.otf
        - asset: assets/fonts/SourceHanSans-Medium.otf
        - asset: assets/fonts/SourceHanSans-Heavy.otf
        - asset: assets/fonts/SourceHanSans-Light.otf
        - asset: assets/fonts/SourceHanSans-Bold.otf
  assets:
    - assets/images/genshin_impact_icon.jpg
    - assets/images/bee.png
    - assets/images/colored_bee.png
    
  
    